version: "3"
services:
  web-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
    volumes: 
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - infobazaar-net
    depends_on:
      - mail-server
      - webapp
      - django-app

  mail-server:
    image: mailhog/mailhog
    container_name: smtp-server
    ports:
      - 8025:8025
      - 1025:1025
    networks: 
    - infobazaar-net

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: infobazaar-app
    restart: always
    networks:
      - infobazaar-net
    tty: true

  django-app:
    build:
      context: ./receipt-env
      dockerfile: Dockerfile
    container_name: infobazaar-receipt
    restart: always
    tty: true
    networks:
      - infobazaar-net

networks:
  infobazaar-net:
    driver: bridge
