version: "3"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8666:8666
    tty: true

  receipts-service:
    build:
      context: ./receipt-env
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    tty: true
