# Generated by Django 5.1.2 on 2024-11-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('code', models.CharField(blank=True, max_length=64, primary_key=True, serialize=False)),
            ],
        ),
    ]
