# Generated by Django 5.1.2 on 2024-11-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_creditpurchasereceipt_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='credits',
        ),
    ]
