# Generated by Django 5.1.2 on 2024-11-03 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_profile_credits'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productfile',
            unique_together={('product', 'id')},
        ),
    ]
