# Generated by Django 5.1.2 on 2024-11-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_productfile_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
