# Generated by Django 5.1.2 on 2024-11-05 22:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_productcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='receipt',
            unique_together={('product', 'buyer')},
        ),
    ]
